In [1]:
import numpy as np

an_array = np.array([[11,12], [21,22], [31,32]])
print(an_array)

[[11 12]
 [21 22]
 [31 32]]


In [7]:
filter = (an_array > 15)
print(filter)

[[False False]
 [ True  True]
 [ True  True]]


In [5]:
print(an_array[filter])

[21 22 31 32]


In [6]:
an_array

array([[11, 12],
       [21, 22],
       [31, 32]])

In [8]:
print(an_array[an_array > 20])

[21 22 31 32]


In [12]:
print(an_array[(an_array > 20) & (an_array < 30)])

[21 22]
