In [2]:
import numpy as np

arr1 = np.zeros((4,3))
print(arr1)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [3]:
arr2 = np.array([1,0,2])
print(arr2)

[1 0 2]


In [6]:
y = arr1 + arr2
print(y)

[[1. 0. 2.]
 [1. 0. 2.]
 [1. 0. 2.]
 [1. 0. 2.]]


In [10]:
arr_col = np.array([[0,1,2,3]])
arr_col = arr_col.T
print(arr_col)

[[0]
 [1]
 [2]
 [3]]


In [11]:
y = arr1 + arr_col
print(y)

[[0. 0. 0.]
 [1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]]


In [12]:
a = np.array([[0,0],[0,0]])
print(a)

[[0 0]
 [0 0]]


In [14]:
b= np.array([1,1])
print(b)

[1 1]


In [16]:
c = 1
print(a+b)
print()
print(a+c)

[[1 1]
 [1 1]]

[[1 1]
 [1 1]]
