In [1]:
import numpy as np

arr = np.array([11,12,13,21,22,23])
print(type(arr))

<class 'numpy.ndarray'>


In [6]:
print(arr.shape)

(6,)


In [9]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)

print(arr[0][1])

[[1 2 3]
 [4 5 6]]
2


In [10]:
print(np.zeros((2,2)))

[[0. 0.]
 [0. 0.]]


In [12]:
print(np.full((2,2), 9))

[[9 9]
 [9 9]]
